# Generated by Django 3.2.9 on 2022-04-21 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydetection', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='numberimage',
        ),
    ]
