# Generated by Django 3.2.9 on 2022-05-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydetection', '0003_numberplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberplate',
            name='number',
            field=models.TextField(),
        ),
    ]
