# Generated by Django 3.2.9 on 2022-05-05 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydetection', '0004_alter_numberplate_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='numberplate',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='numberplate',
            name='timestampin',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='numberplate',
            name='timestampout',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
